/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Environment_LibC */

#ifndef _Included_Environment_LibC
#define _Included_Environment_LibC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Environment_LibC
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Environment_00024LibC_setenv
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     Environment_LibC
 * Method:    unsetenv
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Environment_00024LibC_unsetenv
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
